config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  devise_scope :user do
    get 'login', to: 'devise/registrations#new'
    get 'signup', to: 'devise/registrations#new'
    get 'signout', to: 'devise/registrations#new'
  end
  get '', to: 'home#index'
  get 'contact', to: 'home#contact'
  post 'request_contact', to: 'home#request_contact'
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def contact
    # name = params[:name]
    # email = params[:email]
    # telephone = params[:telephone]
    # message = params[:message]
    # if email.blank?
    #   # flash[:alert] = I18n.t('home.request_contact.no_email')
    #   flash[:alert] = t('home.request_contact.no_email')
    # else# Send an email
    #   ContactMailer.contact_email(email, name, telephone, message).deliver_now
    #   flash[:notice] = t('home.request_contact.email_sent')
    #   # flash[:notice] = I18n.t('home.request_contact.email_sent')
    # end
    # redirect_to root_path

  end


  def request_contact
    name = params[:name]
    email = params[:email]
    telephone = params[:telephone]
    message = params[:message]
    if email.blank?
      # flash[:alert] = I18n.t('home.request_contact.no_email')
      flash[:alert] = t('home.request_contact.no_email')
    else# Send an email
      ContactMailer.contact_email(email, name, telephone, message).deliver_now!
      flash[:notice] = t('home.request_contact.email_sent')
      # flash[:notice] = I18n.t('home.request_contact.email_sent')
    end
    redirect_to root_path
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private

    def sign_up_params
    params.require(:user).permit( :name,
                                  :email,
                                  :password,
                                  :password_confirmation)
    # @user = :name
  # super.Mailer.welcome_email.deliver
  end

  def account_update_params
    params.require(:user).permit( :name,
                                  :email,
                                  :password,
                                  :password_confirmation,
                                  :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/contact.html.haml
%h1 Contact Us
%p Complete the following form to get in touch with us.
-##t('.contact_us')
= form_tag request_contact_path, method: 'post' do
  = label_tag :name, t('.name')
  = text_field_tag :name, '', title: t('.enter_name'), size: 50

  = label_tag :email, t('.email')
  = email_field_tag :email, '', title: t('.enter_email')
  = label_tag :telephone, t('.telephone')
  = telephone_field_tag :telephone, '', title: t('.enter_telephone')
  = label_tag :message,  t('.message')
  = text_field_tag :message, '', title: t('.enter_message'), size: 100
  = submit_tag t('.submit')

app/views/home/index.html.erb
<title>Home</title>
<header>
  <% if user_signed_in? %>
  You have successfully logged in!
  <% else %>
  "Welcome to the Booking App. Please select the login button to continue to your account."
  <% end %></header>
<!--<script type="text/javascript">-->
<!--    $(function() {-->
<!--        $("table tr:nth-child(even)").addClass("striped");-->
<!--    });-->
<!--</script>-->
<!--<include></include>-->
<%= javascript_include_tag('TableStyle.js') %>
<body>
<%#= link_to("Make a booking", new_booking_path) %>
<% if user_signed_in? %>
<p></p>
  <title style="align-content: center">Main Page</title>
  <p></p>

  <table id ="InfoTable", style="align-self: center", width="600px", border="5">
    <thead>
    <ta align="center"> Bookings Menu</ta>
    <td>Link</td>
    <td>Functionality</td>
    </thead>
    <tbody>
<!--    <tr>-->
<!--      <td><%#= link_to("Make a booking", new_booking_path) %>-->
<!--      </td>-->
<!--      <td><%#= "Create a new booking"%>-->
<!--    </td>-->
<!--    </tr>-->
<!--    <tr>-->
<!--      <td><%#= link_to("Show My bookings", bookings_path) %>-->
<!--      </td>-->
<!--      <td><%#= "View your booking details"%>-->
<!--      </td>-->
<!--    </tr>-->
<!--    <tr>-->
<!--      <td></td>-->
<!--      <td><%#= link_to("Edit My bookings", edit_booking_path(Booking.find_by_user_id(current_user.email))) %>-->
<!--      </td>-->
<!--      <td><%#= "Edit your booking "%>-->
<!--      </td>-->
<!--    </tr>-->

        </tbody>

  </table>
  <% end %>
</body>
<%#=
<!-- "HOME PAGE" -->
<!-- </header> -->
<!-- <body>
  <%# <% if user_signed_in? %>



<script type="text/javascript" charset="utf-8">
    var tableRows = document.getElementsByTagName('tr');

    for (var i = 0; i < tableRows.length; i++) {
        tableRows[i].style.backgroundColor = (i % 2)?"red":"yellow";
    }

</script>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <!-- <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small> -->
  <nav>
    <div class="container">

      <ul>
        <li><%= link_to "About",   '#' %></li>
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
      </ul>
    </div>
  </nav>
</footer>

app/views/layouts/_navigation.html.erb
<%= stylesheet_link_tag    '/partials/layout/navigation', media: 'all', 'data-turbolinks-track': 'reload' %>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">

    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= image_tag "bookLogo.png" %>
      <a class="navbar-brand" href="/">Booking Centres Inc</a>
      <%= link_to '', class: 'navbar-brand' %>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>

      <ul class="nav navbar-nav navbar-right">

        <!-- <button type="button" name="logout", >Logout</button> -->
        <% if user_signed_in? %>
          <li>Signed in as <%= current_user.email %></li>

          <li>
            <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "button") %>
          </li>
<!--          <div class="dropdown"; >-->
<!--            <button class="dropbtn">Booking Menu</button>-->
<!--            <div class="dropdown-content">-->
              <%#=  link_to('Edit Details', edit_user_registration_path, class: "button") %>
              <%#= link_to('Make Booking', new_booking_path, class: "button") %>
              <%#= link_to('Show Bookings', bookings_path, class: "button") %>
<!--              <a href="DeleteBooking.php">Delete My Booking</a>-->
<!--            </div>-->
          <li>
            <%= link_to('Edit Details', edit_user_registration_path, class: "button") %>
          </li>
<!--          <li>-->
            <%#= link_to('Make Booking', new_booking_path, class: "button") %>
<!--          </li>-->
<!--          <li>-->
            <%#= link_to('Show Bookings', bookings_path, class: "button") %>
<!--          </li>-->
<!--          <li>-->
            <%#= link_to('Locations', les_centres_path, class: "button") %>
<!--          </li>-->
        <% else %>
          <li>
            <%= link_to('Login', new_user_session_path, class: "button") %>
          </li>
          <li>
            <%= link_to('Sign Up', new_user_registration_path, class: "button") %>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JG00989Cw</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= render 'layouts/navigation' %>
    <div class="container">
     <%= yield %>

   </div>
   <%= render 'layouts/footer' %>

  </body>
</html>

app/views/layouts/application.html.haml
<!DOCTYPE html>
<html>
  <head>
    <title>Login</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>



    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  %body
    -flash.each do |key, value|
    = content_tag :div, content_tag(:p, value), id: "#{key}" unless value.blank?

  -#<body>
  -#  <!-- <p class="notice"><%= notice %></p> -->
  -#  <!-- <p class="alert"><%= alert %></p>
  -#  <%= yield %> -->
    
  -#</body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>